server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: phone
          uri: http://localhost:8082
          predicates:
            - Path=/lostPhones/**, /phones/**, 
        - id: lostservice
          uri: http://localhost:8083
          predicates:
            - Path=/phoneChanges/**, 
        - id: gps
          uri: http://localhost:8084
          predicates:
            - Path=/destinations/**, 
        - id: dashboard
          uri: http://localhost:8085
          predicates:
            - Path=, /gpsInfos/**, /phones/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: phone
          uri: http://phone:8080
          predicates:
            - Path=/lostPhones/**, /phones/**, 
        - id: lostservice
          uri: http://lostservice:8080
          predicates:
            - Path=/phoneChanges/**, 
        - id: gps
          uri: http://gps:8080
          predicates:
            - Path=/destinations/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
