apiVersion: apps/v1
kind: Deployment
metadata:
  name: lostservice
  labels:
    app: lostservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lostservice
  template:
    metadata:
      labels:
        app: lostservice
    spec:
      containers:
        - name: lostservice
          image: "username/lostservice:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
